version: "3.8"
services:
  es01:
    build: elasticsearch
#    image: elasticsearch:7.17.6
    container_name: es01
    environment:
      - xpack.security.enabled=false
      - node.name=es01
      - node.data=true
      - node.ingest=false
      - node.master=true
      - node.ml=false
      - search.remote.connect=false
      - network.host=es01
      - cluster.name=LiferayElasticsearchCluster01
      - cluster.initial_master_nodes=es01
      #- discovery.seed_hosts=es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - volume-elasticsearch74-01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - network-liferay74-tomcat
  es02:
    build: elasticsearch
    #image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: es02
    environment:
      - xpack.security.enabled=false
      - node.name=es02
      - node.data=true
      - node.ingest=true
      - node.master=true
      - node.ml=false
      - search.remote.connect=false
      - network.host=es02
      - cluster.name=LiferayElasticsearchCluster01
      - cluster.initial_master_nodes=es01
      #- discovery.seed_hosts=es02,es03
      # http://localhost:9400/_cluster/health
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - volume-elasticsearch74-02:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
      - 9500:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - network-liferay74-tomcat
  liferay74-tomcat-1:
    build: liferay74-tomcat
    container_name: liferay74-tomcat-1
    depends_on:
      - mysql
      - es01
      - es02
    networks:
      - network-liferay74-tomcat
    ports:
      - 8081:8080
      - 127.0.0.1:11311:11311
    volumes:
      - volume-liferay74-tomcat-data:/opt/liferay/data
      - volume-liferay74-tomcat-1-work:/opt/liferay/tomcat/work
#  liferay74-tomcat-2:
#    build: liferay74-tomcat
#    container_name: liferay74-tomcat-2
#    depends_on:
#      - mysql
#      - es01
#      - es02
#    networks:
#      - network-liferay74-tomcat
#    ports:
#      - 8082:8080
#      - 127.0.0.1:21311:11311
#    volumes:
#      - volume-liferay74-tomcat-data:/opt/liferay/data
#      - volume-liferay74-tomcat-2-work:/opt/liferay/tomcat/work
  haproxy:
    build: haproxy
    container_name: haproxy
    networks:
      - network-liferay74-tomcat
    ports:
      - 9002:80
      - 9999:9999
  mysql:
    image: mysql:8.0.31-oracle
    container_name: mysql8
    networks:
      - network-liferay74-tomcat
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: liferay
      MYSQL_DATABASE: lportal
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: liferay
    volumes:
      - volume-mysql8:/var/lib/mysql
networks:
  network-liferay74-tomcat:
    name: network-liferay74-tomcat
volumes:
  volume-elasticsearch74-01:
  volume-elasticsearch74-02:
  volume-liferay74-tomcat-data:
  volume-liferay74-tomcat-1-work:
  volume-liferay74-tomcat-2-work:
  volume-mysql8:
